stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "rss-api-server"
  DOCKER_TAG: "latest"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

deploy:
  stage: deploy
  image: ruby:2.6
  script:
    - apt-get update -y
    - apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$REMOTE_HOST "docker pull $DOCKER_IMAGE:$DOCKER_TAG && docker run -d $DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main
